### ISSUE TITLE
Unable to connecto skype-web

### ISSUE THREAD

**Issue by frakseno** [sdimkov/hubot-skype-web#10]
I have set this up in OSX, running 2.0 version of phantomjs. When I try to start hubot, i get the following in the console:

[Thu Nov 12 2015 11:55:06 GMT-0500 (EST)] DEBUG Loading adapter skype-web
phantom stdout: TypeError: '[object BlobConstructor]' is not a constructor (evaluating 'new Blob')

phantom stdout:   https://swx.cdn.skype.com/v/1.17.77/js/fullExperience.min.js:324
  https://swx.cdn.skype.com/v/1.17.77/js/fullExperience.min.js:324
  https://swx.cdn.skype.com/v/1.17.77/js/fullExperience.min.js:324
  https://swx.cdn.skype.com/v/1.17.77/js/fullExperience.min.js:324 in g
  https://swx.cdn.skype.com/v/1.17.77/js/fullExperience.min.js:324
  https://swx.cdn.skype.com/v/1.17.77/js/fullExperience.min.js:324 in g
  https://swx.cdn.skype.com/v/1.17.77/js/fullExperience.min.js:324
  https://swx.cdn.skype.com/v/1.17.77/js/fullExperience.min.js:324 in g
  https://swx.cdn.skype.com/v/1.17.77/js/fullExperience.min.js:324
  https://swx.cdn.skype.com/v/1.17.77/js/fullExperience.min.js:324 in g
  https://swx.cdn.skype.com/v/1.17.77/js/fullExperience.min.js:324
  https://swx.cdn.skype.com/v/1.17.77/js/fullExperience.min.js:324 in g
  https://swx.cdn.skype.com/v/1.17.77/js/fullExperience.min.js:324
  https://swx.cdn.skype.com/v/1.17.77/js/fullExperience.min.js:324 in g
  https://swx.cdn.skype.com/v/1.17.77/js/fullExperience.min.js:324
  https://swx.cdn.skype.com/v/1.17.77/js/fullExperience.min.js:324 in g
  https://swx.cdn.skype.com/v/1.17.77/js/fullExperience.min.js:324
  https://swx.cdn.skype.com/v/1.17.77/js/fullExperience.min.js:324 in g
  https://swx.cdn.skype.com/v/1.17.77/js/fullExperience.min.js:324
  https://swx.cdn.skype.com/v/1.17.77/js/fullExperience.min.js:324 in g
  https://swx.cdn.skype.com/v/1.17.77/js/fullExperience.min.js:324
  https://swx.cdn.skype.com/v/1.17.77/js/fullExperience.min.js:324 in g
  https://swx.cdn.skype.com/v/1.17.77/js/fullExperience.min.js:324
  https://swx.cdn.skype.com/v/1.17.77/js/fullExperience.min.js:324 in g
  https://swx.cdn.skype.com/v/1.17.77/js/fullExperience.min.js:324
  https://swx.cdn.skype.com/v/1.17.77/js/fullExperience.min.js:324 in g
  https://swx.cdn.skype.com/v/1.17.77/js/fullExperience.min.js:324
  https://swx.cdn.skype.com/v/1.17.77/js/fullExperience.min.js:324 in g
  https://swx.cdn.skype.com/v/1.17.77/js/fullExperience.min.js:324
  https://swx.cdn.skype.com/v/1.17.77/js/fullExperience.min.js:324 in g
  https://swx.cdn.skype.com/v/1.17.77/js/fullExperience.min.js:324
  https://swx.cdn.skype.com/v/1.17.77/js/fullExperience.min.js:324 in g
  https://swx.cdn.skype.com/v/1.17.77/js/fullExperience.min.js:324
  https://swx.cdn.skype.com/v/1.17.77/js/fullExperience.min.js:324 in g
  https://swx.cdn.skype.com/v/1.17.77/js/fullExperience.min.js:324
  https://swx.cdn.skype.com/v/1.17.77/js/fullExperience.min.js:324 in g
  https://swx.cdn.skype.com/v/1.17.77/js/fullExperience.min.js:324
  https://swx.cdn.skype.com/v/1.17.77/js/fullExperience.min.js:324 in g
  https://swx.cdn.skype.com/v/1.17.77/js/fullExperience.min.js:324
  https://swx.cdn.skype.com/v/1.17.77/js/fullExperience.min.js:324

[Thu Nov 12 2015 11:55:57 GMT-0500 (EST)] ERROR SkypeWeb adapter failed to login!
[Thu Nov 12 2015 11:55:57 GMT-0500 (EST)] ERROR Error: SkypeWeb adapter failure in initial login!
  at Object.error (/Users/ashneyder/dev/hubot/node_modules/hubot-skype-web/src/skypeweb.coffee:56:17, <js>:75:15)
  at [object Object]._onTimeout (/Users/ashneyder/dev/hubot/node_modules/hubot-skype-web/src/skypeweb.coffee:115:18, <js>:142:84)
  at Timer.listOnTimeout (timers.js:92:15)

**Comment by sdimkov** [comment]
I believe this is a problem/bug in PhantomJS. Please check if any other build for OSX gets around this. 

More details:
The error I see indicates troubles creating blobs in JS. 
PhantomJS 2.0 supports blobs (1.9 does not). What is your output of `phantomjs -version` ?
You can read more on the subject [here](https://github.com/ariya/phantomjs/issues/11013) and [here](http://www.finallybinary.com/blob-support-in-phantomjs/).

I hope that helps :)

**Comment by sdimkov** [comment]
@ashneyder I'm closing this for now. Please feel free to reopen if you have anything new to add about the problem or any possible solution.
