### ISSUE TITLE
Hubot not coming online

### ISSUE THREAD

**Issue by sbozzie** [sdimkov/hubot-skype-web#11]
Trying to install hubot for use as a skype bot.
I have a windows install of hubot, which starts up with the hubot command in CMD as follows:

```
C:\hubot\node_modules\.bin>hubot
[Sun Nov 15 2015 19:21:20 GMT+0000 (GMT Standard Time)] INFO SkypeWeb adapter logged in successfully!
[Sun Nov 15 2015 19:21:20 GMT+0000 (GMT Standard Time)] INFO SkypeWeb adapter configured to reconnect every 240 minutes
```

After this, there is no output in the window, and the bot does not appear on-line on Skype, or respond to any commands. Any tips on debugging, or what might be going on here would be appreciated

**Comment by sbozzie** [comment]
Fixed using the instructions at https://github.com/github/hubot/issues/812

**Comment by sdimkov** [comment]
Thanks for updating us on the solution!

And sorry I didn't find time to reply to this earlier.
