### ISSUE TITLE
How to handle Captcha

### ISSUE THREAD

**Issue by jaredallard** [sdimkov/hubot-skype-web#3]
Currently, if you make the mistake I did, have the wrong username it (expectedly) fails. After a few times Skype drops a Captcha on you. Anyway to handle this programmatically?

**Comment by sdimkov** [comment]
I don't think there is much to be done on handling this. Captchas are designed to stop robots. Perhaps the code that interacts with the login form could check for captcha and fail with a better error message?

I personally haven't explored this topic. Do they filter per IP or per account? I mean do you see captcha as soon as you load the login page or you see it once you type your username? Also did the captcha go away once you logged correctly?

**Comment by jaredallard** [comment]
That's what I was thinking.

Per IP, so yes, regardless of browser and before username was entered. It did not go away once logged in correctly. It went away after around an hour.

**Comment by sdimkov** [comment]
Well I'm on a vacation in Greece so I won't be writing any code these days. But I can take a look at PRs  :)

**Comment by sdimkov** [comment]
@jaredallard I'll close this given that I don't see what more can we do on this subject. Please see if my commit helps.
