### ISSUE TITLE
Frequent Poll response error

### ISSUE THREAD

**Issue by sivakumar-kailasam** [sdimkov/hubot-skype-web#4]
We've been running into `ERROR Poll response error 729: You must create an endpoint before performing this operation.` way too often and hubot's responses are lost. Any clue what could be wrong?

**Comment by sdimkov** [comment]
I've experienced this problem as well but I haven't found the time to fully investigate and resolve it.
You can try configuring the setup for more frequent reconnects.

More info on the problem:
I believe at some point the web client negotiates another endpoint for communication. So when that happens you start getting such errors. Skype's web client also makes a POST call to /users/ME/endpoints/<<ID>>/active to update presence and perhaps to be told to redirect to another endpoint.
An improvement to the current code would be to reconnect upon receiving error 729
An even better solution would be to investigate /active requests and endpoint negotiation.

p.s. If not obvious this project is based on reverse-engineering Skype for Web. Microsoft does not provide any API or docs for such 3rd party automation.

**Comment by sivakumar-kailasam** [comment]
Thanks for the explanation @sdimkov, just wanted to check if you faced this too. Will see if I can work on that and send a PR :smile:

**Comment by sdimkov** [comment]
Related to conversation at #5

**Comment by sivakumar-kailasam** [comment]
For the past day I haven't noticed issues with the latest update, but I'll monitor for a day or two before I'll close this.

**Comment by sivakumar-kailasam** [comment]
Noticed those 729's again. Will probably have to investigate further. Will keep this thread posted if I find anything new

**Comment by Leandros** [comment]
This might help: https://github.com/EionRobb/skype4pidgin/blob/master/skypeweb/skypeweb_messages.c#L1073

**Comment by BigBear0812** [comment]
Getting the same error When deployed to heroku. I have included the logs below. let me know if you would like any more information about the current configuration.

http://pastebin.com/c7C16QeJ

**Comment by clbrsantana** [comment]
I'm getting the same error for months now, and it happens all the time, leaving hubot without responses. I noticed it sometimes work when I first connect to other wifi, or when I first try other skype-web branch (like skype-web-no-cors ou skype-web-cdp). I also get into the error `ERROR Timeout in waiting for login success!` frequently. Dunno if there's any relation, but the information may be important. I run hubot locally from my mac at work, and I didn't get this errors when running it from home, though I rarely run hubot at home.
