### ISSUE TITLE
Handle Live Accounts

### ISSUE THREAD

**Issue by bkmeneguello** [sdimkov/hubot-skype-web#7]
It's possible to handle live logins? When the username is set the page is redirected to the live login and the current login fails by timeout.

**Comment by sdimkov** [comment]
Hi there,

Yes it is possible. It would a few extra lines of code during the login process.

I wonder is it approriate to recognize Windows Live accounts based on containing '@' or that should be explicitly set in the configuration? Also can a regular skype name contain '@' ?

**Comment by bkmeneguello** [comment]
It's a great idea. Skype usernames cannot contain '@'.

**Comment by sdimkov** [comment]
@bkmeneguello please check if v0.9.10 works for you
