### ISSUE TITLE
which phantomjs version is required  for hubot-skype-web?

### ISSUE THREAD

**Issue by gasolin** [sdimkov/hubot-skype-web#9]
Hi, I installed 1.9.x phantomjs via command

```
npm install phantomjs --save
```

But still failed to login with hubot-skype-web.

Does hubot-skype-web require phantomjs 2 or something else?

**Comment by sdimkov** [comment]
Hi,

I recommend using latest version of phantomJS (2.0).

On Windows systems it should work with both 1.9 and 2.0 or at least it used to work on my Windows systems when I was developing it.

On linux systems it works only with 2.0. I haven't investigated why 1.9 fails to render skype's web client. You can download 2.0 for linux [here](https://groups.google.com/forum/#!searchin/phantomjs/dimkov/phantomjs/CAasXq1Yzz0/fyjIm58cXk8J). There is also a small section in the README on this issue.

**Comment by gasolin** [comment]
Thanks for help, the question section is clear
